version: 1.0.0.{build}
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\CephasPAD.Utilities.Slugify.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: dotnet restore
build:
  publish_nuget: true
  verbosity: normal
test:
  assemblies:
    only:
    - CephasPAD.Utilities.Slugify.Tests.dll
artifacts:
- path: 'src\CephasPAD.Utilities.Slugify\bin\Release\netstandard2.0'
deploy:
- provider: NuGet
  api_key:
    secure: +c87PhQtch62p62tl32uKGCVC136YC/qczLzOxfTW6yFqf3HF/R3+eQKQUN11HW5
  skip_symbols: false
  on:
    branch: master