version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet build
after_build:
  # For once the build has completed
test_script:
  # restore packages for our unit tests
  - cmd: dotnet restore --verbosity m
  # run the unit tests (requires changing into the test directory)
    - cmd: dotnet mstest
deploy:
  provider: NuGet
  server:                  # remove to push to NuGet.org
  api_key:
    secure: Ga8L34jYe2krfsZhCS9Hvva8QofXKf1zcUyeDHi4X19GsIfYzCPhAtc4eI2cfTFn
  skip_symbols: false
  symbol_server:           # remove to push symbols to SymbolSource.org
  artifact: /.*\.nupkg/